"""
Django settings for scm project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k-0)0bbkazqb%$v#zhxsncb_d3++go6edg!kp_at5oi)+&!7ay'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['scm-backend.herokuapp.com','127.0.0.1']

#
#ALLOWED_HOSTS = [ '10.0.0.20','10.0.0.20:3000','localhost','localhost:3000','localhost:8000',
#                '10.0.0.12','10.0.0.12:3000', '10.0.0.12',
#                '10.0.0.25',
#                '10.0.0.25:3000',
#                '10.0.0.25:8000',
#                '10.0.0.12:8000',
#                '10.0.0.25','10.0.0.25:3000','127.0.0.1', '127.0.0.1:3000','127.0.0.1:8000','205.147.98.252:8000', '205.147.98.252']
#
#

# Application definition
INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_docs',
    'rest_framework.authtoken',
    'corsheaders',

    #Project
    'api',
    'scm',  
    

    #Third party
    'drf_multiple_model',
        
]   



REST_FRAMEWORK_DOCS = {
'HIDE_DOCS': False # Default: False
}

REST_FRAMEWORK = {
'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
),
'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework.authentication.TokenAuthentication',

),

'DEFAULT_PARSER_CLASSES': (
    'rest_framework.parsers.JSONParser',
    'rest_framework.parsers.MultiPartParser',
    'rest_framework.parsers.FileUploadParser',
    
),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_WHITELIST = ('*')

# CORS_ORIGIN_WHITELIST = (
#     '10.0.0.25',
#     '10.0.0.25:3000',
#     '10.0.0.25:8000',
#     '10.0.0.12',
#     '10.0.0.12:8000',
#     'localhost:3000',
#     'localhost',
#     'localhost:8000',
#     '127.0.0.1:8000',
#     '127.0.0.1',
#     '127.0.0.1:3000',
#     '205.147.98.252:8000',
#     '205.147.98.252',



# )

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

##============================================##
CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken',
    'token',
    'x-device-id',
    'x-device-type',
    'x-push-id',
    'dataserviceversion',
    'maxdataserviceversion'
    )
CORS_ALLOW_METHODS = (
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS'
        )
##============================================##



ROOT_URLCONF = 'scm.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'scm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
#     'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }

    # 'default': {
    #    'ENGINE': 'djongo',
    #    'NAME': 'api_july14',
    # }

    #  'default':
    #  {
    #  'ENGINE': 'djongo',
    #  'NAME': 'just_books',
    # #  'HOST':'localhost:27017',
    # 'HOST':'mongodb://mongoadmin:Mongoadmin_123#@localhost:27017/just_books?authSource=admin',
    #  'USERNAME':'mongoadmin',
    #  'PASSWORD':'Mongoadmin_123#',
    #  'AUTH_SOURCE':'admin'
    #  }

    
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'api_new',
            'USER': '',
            'PASSWORD': '',
            'HOST': 'localhost',
            'PORT': '',
        }
    }




# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M",
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')


MEDIA_URL = '/media/'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FILE_UPLOAD_URL = '/uploads/'
FILE_UPLOAD_ROOT = os.path.join(BASE_DIR, 'uploads')


CELERY_BROKER_URL = 'amqp://localhost'


CELERY_IMPORTS = (
    'api.tasks',
)